version: '3.3'

services:
  mongodb:
    image: mongo:latest
    container_name: my_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: c67vBNh24dWE
    volumes:
      - ./mongo_data:/data/db

  app:
    image: pankaj2212/dnslookup:0.2.0
    environment:
      MONGO_URI: "mongodb://root:c67vBNh24dWE@mongodb:27017/"
      DB_NAME: "domain_lookup"
      COLLECTION_NAME: "queries"
      APP_VERSION: "0.2.0"
    depends_on:
      - mongodb
    ports:
      - "3000:3000" 

