apiVersion: v1
kind: Secret
metadata:
  name: {{ include "my-app.fullname" . }}
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongodb.MONGO_INITDB_ROOT_USERNAME | b64enc | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongodb.MONGO_INITDB_ROOT_PASSWORD | b64enc | quote }}
  MONGO_URI: {{ .Values.mongodb.MONGO_URI | b64enc | quote }}
  DB_NAME: {{ .Values.mongodb.DB_NAME | b64enc | quote }}
  COLLECTION_NAME: {{ .Values.mongodb.COLLECTION_NAME | b64enc | quote }}
