name: Build and Deploy

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: read

jobs:
  Lint_Check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"

    - name: Install dependencies
      working-directory: ./app
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        pip install -r requirements.txt

    - name: Lint with flake8
      working-directory: ./app
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
  Build_and_push:
    needs: Lint_Check
    runs-on: ubuntu-latest

    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      working-directory: ./app
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/dnslookup:${GITHUB_REF_NAME} .
        docker push ${{ secrets.DOCKER_USERNAME }}/dnslookup:${GITHUB_REF_NAME}

    - name: Update Helm Chart Version
      working-directory: ./kubernetes-setup/dnslookup-helm
      run: |
        sed -i "s/^version:.*/version: ${GITHUB_REF_NAME}/" Chart.yaml

    - name: Package Helm Chart
      working-directory: ./kubernetes-setup/dnslookup-helm
      run: |
        helm package .

    - name: Upload Helm Chart
      uses: actions/upload-artifact@v3
      with:
        name: dnslookup-helm-chart
        path: ./kubernetes-setup/dnslookup-helm/*.tgz
